In [25]:
import requests
import pandas as pd
from io import StringIO

BASE_URL="https://aviationweather.gov/adds/dataserver_current/httpparam"
    
stationString = "KOAK,KHWD,KSFO,KHAF,KSQL,KPAO,KNUQ,KSJC,KRHV,KC83,KTCY"
query = {"dataSource":"metars","requestType":"retrieve","format":"csv","stationString":stationString, "hoursBeforeNow":1}

data = requests.get(BASE_URL, params=query)

In [27]:
buffer = StringIO(data.text)
df = pd.read_csv(buffer, skiprows=5)
df = df.drop(["raw_text"], axis=1)
df

,station_id,observation_time,latitude,longitude,temp_c,dewpoint_c,wind_dir_degrees,wind_speed_kt,wind_gust_kt,visibility_statute_mi,...,maxT24hr_c,minT24hr_c,precip_in,pcp3hr_in,pcp6hr_in,pcp24hr_in,snow_in,vert_vis_ft,metar_type,elevation_m
0,KSQL,2022-02-03T16:58:00Z,37.52,-122.25,9.0,3.0,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,1.0
1,KSFO,2022-02-03T16:56:00Z,37.62,-122.37,10.6,6.1,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SPECI,2.0
2,KTCY,2022-02-03T16:55:00Z,37.68,-121.43,12.0,-2.0,290,6,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,51.0
3,KNUQ,2022-02-03T16:55:00Z,37.40,-122.05,8.0,-1.0,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SPECI,9.0
4,KHAF,2022-02-03T16:55:00Z,37.52,-122.50,9.0,6.0,0,0,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,11.0
5,KC83,2022-02-03T16:55:00Z,37.83,-121.62,11.0,3.0,260,5,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,16.0
6,KHWD,2022-02-03T16:54:00Z,37.67,-122.12,8.9,-0.6,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,9.0
7,KSJC,2022-02-03T16:53:00Z,37.37,-121.92,7.8,-1.1,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,13.0
8,KOAK,2022-02-03T16:53:00Z,37.72,-122.23,9.4,2.8,170,3,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,3.0
9,KPAO,2022-02-03T16:47:00Z,37.47,-122.12,8.0,1.0,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,2.0
10,KTCY,2022-02-03T16:35:00Z,37.68,-121.43,11.0,-2.0,270,8,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,51.0
11,KC83,2022-02-03T16:35:00Z,37.83,-121.62,9.0,3.0,240,6,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SPECI,16.0
12,KHAF,2022-02-03T16:35:00Z,37.52,-122.50,6.0,6.0,0,0,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,11.0
13,KNUQ,2022-02-03T16:35:00Z,37.40,-122.05,7.0,-1.0,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,9.0
14,KHAF,2022-02-03T16:15:00Z,37.52,-122.50,5.0,5.0,0,0,NaN,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,11.0
15,KTCY,2022-02-03T16:15:00Z,37.68,-121.43,11.0,-2.0,270,7,13.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,51.0
16,KNUQ,2022-02-03T16:15:00Z,37.40,-122.05,5.0,-1.0,0,0,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,METAR,9.0
17,KC83,2022-02-03T16:15:00Z,37.83,-121.62,7.0,2.0,260,6,NaN,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SPECI,16.0